import json, glob

QUICK_ANSWERS = {
    # Historical stories (Hall of Filth)
    "hall-of-filth-appalachian-state-michigan": "In 2007, Appalachian State — a Division I-AA team — beat #5 Michigan 34-32 in the Big House, one of the biggest upsets in college football history. Most sportsbooks didn't even post a line because FCS-vs-FBS matchups were considered non-competitive. A $1 bet at the estimated spread would have returned a massive payout.",
    "biggest-longshot-wins-sports-history": "The biggest longshot wins in sports history include Leicester City at 5000-to-1 (2015-16 Premier League), Buster Douglas knocking out Mike Tyson at 42-to-1, Greece winning Euro 2004 at 150-to-1, and the 2004 Red Sox coming back from 0-3. Each one is reframed here as what a $1 bet would have returned.",
    "biggest-parlay-wins-ever": "The biggest parlay wins in betting history turned tiny stakes into life-changing payouts by stringing together multiple unlikely outcomes on a single ticket. Multi-leg parlays multiply odds together — the more legs, the bigger the payout and the smaller the chance. These are the ones that actually hit.",
    "hall-of-filth-buster-douglas": "Buster Douglas knocked out Mike Tyson in the 10th round on February 11, 1990, at approximately 42-to-1 odds. A $1 bet would have returned roughly $42. Many Las Vegas sportsbooks didn't even post the fight because nobody expected Douglas to compete, let alone win.",
    "hall-of-filth-gamestop": "In January 2021, Reddit's r/WallStreetBets coordinated a massive buying spree of GameStop stock, squeezing hedge funds that had shorted it. GME went from around $17 to $483 in weeks. A $1 investment at $17 would have returned roughly $28 at the peak — a 2,700% gain driven entirely by internet chaos.",
    "hall-of-filth-leicester-city": "Leicester City won the 2015-16 Premier League at approximately 5000-to-1 odds, the most improbable title win in major professional sports history. They'd nearly been relegated the season before. A $1 bet placed before the season would have returned roughly $5,000.",
    "hall-of-filth-miracle-on-ice": "In 1980, a team of American college hockey players beat the four-time defending Olympic gold medalist Soviet Union 4-3 at Lake Placid. Precise betting odds from 1980 are hard to verify, but the Soviets were enormous favorites. It became the most famous upset in Olympic history.",
    "hall-of-filth-red-sox-2004": "The 2004 Boston Red Sox became the first MLB team ever to come back from a 0-3 deficit in a playoff series, beating the Yankees in the ALCS and then sweeping the Cardinals to win the World Series. In 135 years of baseball, no team had done it before.",
    "strangest-bets-ever-made": "The strangest bets in history include a man who ate an entire Cessna airplane over two years to win a bet, wagers on papal elections, bets on alien contact, and a gambler who legally changed his name to a poker site's URL for sponsorship money. These wagers actually happened.",
    "hall-of-filth-trump-2016": "Donald Trump's odds to win the 2016 presidential election started at roughly 150-to-1 in some prediction markets. Even on election night, markets had Hillary Clinton at 85%+ probability. A $1 bet on Trump at peak longshot odds would have returned approximately $150.",
    "what-would-1-dollar-have-paid-famous-bets": "A $1 bet on Leicester City's 2015-16 title would have returned roughly $5,000. On Buster Douglas over Tyson, about $42. On Trump in 2016 at peak longshot pricing, approximately $150. This page reframes history's most famous upsets through the $1 lens to show what was actually at stake.",

    # Roundups and ranked lists
    "altcoin-moonshot-bets": "Altcoin moonshot prediction markets let you bet on whether specific cryptocurrencies will hit extreme price targets. These are the crypto equivalent of longshot sports bets — low probability, high potential payout. Platforms like Kalshi and Polymarket offer contracts on Bitcoin, Ethereum, and altcoin price milestones.",
    "best-bets-for-a-dollar-this-week": "This week's best $1 bets are curated from prediction markets and sportsbooks — the wagers with the most entertaining risk-to-reward ratio right now. Updated weekly with markets that are weird enough to screenshot and cheap enough to not care if they lose.",
    "best-bets-this-weekend": "This weekend's best bets span Saturday and Sunday across sports, fights, and prediction markets. Each pick is framed as what $1 returns, because the best weekend bets are the ones entertaining enough to follow even if you don't place them.",
    "best-bets-under-5-dollars": "The best bets you can make for under $5 include prediction market contracts starting at $0.01, sportsbook minimum bets, and parlay tickets that combine cheap legs into bigger potential payouts. Platforms like Kalshi let you start at $1 per contract.",
    "best-dollar-bets-this-month": "This month's best dollar bets are the picks that made the daily board for their entertainment value, payout potential, or sheer absurdity. Updated monthly with the bets worth remembering — or forgetting, depending on how they resolve.",
    "best-futures-bets-right-now": "The best futures bets right now are long-term wagers on championships, MVP awards, and season outcomes where the odds haven't fully adjusted yet. Futures lock in your price early — if you're right about a dark horse before the market catches on, $1 can go a long way.",
    "biggest-betting-upsets-this-year": "The biggest betting upsets of 2026 so far — the results that made sportsbooks and prediction markets look foolish. Each one is shown as what $1 would have returned. Updated as chaos happens throughout the year.",
    "biggest-payouts-this-week": "This week's biggest potential payouts on prediction markets — the contracts where $1 returns the most if the event happens. These are extreme longshots by definition. Most will lose. That's the whole point.",
    "biggest-single-game-upsets-by-sport": "The biggest single-game upset in every major sport: the NFL, NBA, MLB, college football, soccer, boxing, and MMA each have a defining shock result. Every upset is reframed as what a $1 bet would have returned to show the scale of the improbability.",
    "celebrity-prediction-markets": "Celebrity prediction markets let you bet on award show outcomes, career moves, public scandals, and pop culture events. Platforms like Kalshi offer contracts on Oscars, Grammys, and other entertainment outcomes. These are some of the most entertaining markets to follow because the outcomes are genuinely unpredictable.",
    "craziest-bets-this-week": "This week's craziest bets from prediction markets, sportsbooks, and prop bet platforms. Updated every Friday with the wagers that exist for reasons nobody can fully explain — but that someone is definitely going to take.",
    "crypto-vs-sports-betting": "Crypto prediction markets and sports betting both let you wager on outcomes, but crypto markets cover non-sports events, trade on blockchain exchanges, and often have no minimum bet. Sports betting offers deeper liquidity and more familiar formats. For a $1 stake, prediction markets generally offer more variety and longer odds.",
    "daily-email": "The Dollar Bets daily email delivers three curated prediction market picks to your inbox every morning. Three bets, three quips, one dollar framing. It's free, it takes 30 seconds to read, and it's the fastest way to find out what weird things the internet is betting on today.",
    "entertainment-prop-bets": "Entertainment prop bets let you wager on Oscars, Emmys, reality TV outcomes, box office numbers, and other Hollywood events. These are proposition bets on specific entertainment occurrences rather than final outcomes. Prediction markets and some sportsbooks offer them year-round.",
    "free-dollar-bet-promos": "Several sportsbooks and prediction market platforms offer free bet promotions for new users. These let you place a wager without risking your own money. Promotions change frequently — this page tracks current verified offers from regulated platforms.",
    "funny-betting-odds-today": "Today's funniest betting odds from prediction markets and sportsbooks — the markets that exist for no good reason and pay surprisingly well if they hit. Updated daily with the wagers most likely to make you laugh before they make you lose a dollar.",
    "hall-of-filth": "The Hall of Filth is Dollar Bets' collection of the greatest longshot wins in history. Leicester City at 5000-to-1, Buster Douglas at 42-to-1, the Miracle on Ice, Trump 2016 — each story is told through what a $1 bet would have returned. These are the bets that broke the model.",
    "how-to-read-prediction-market-odds": "Prediction market odds are displayed as contract prices between $0.01 and $0.99. The price represents the market's estimated probability. A contract at $0.10 means the market thinks there's a 10% chance of the event happening. If you buy at $0.10 and it resolves Yes, you get $1 back — a $1 bet returns $10.",
    "supreme-court-prediction-markets": "Supreme Court prediction markets let you trade on ruling outcomes, justice retirements, and nomination confirmations. Platforms like Kalshi and Polymarket offer contracts on major SCOTUS decisions. These markets often move faster than legal commentary because traders price in information as it emerges.",
    "why-we-use-the-dollar-framing": "Dollar Bets frames every market as what $1 returns because it's the simplest way to compare wildly different bets. Whether it's a prediction market contract at $0.02 or a +5000 sports longshot, translating to '$1 pays $X' makes the payout instantly understandable without knowing how odds formats work.",
    "will-bitcoin-hit-price-target": "Prediction markets currently offer contracts on whether Bitcoin will hit various price targets by specific dates. These markets reflect real-time trader sentiment — not analyst predictions. The $1 framing shows what you'd get back if Bitcoin actually hits the target, which makes the bet feel more concrete than a price chart.",
    "what-is-a-futures-bet": "A futures bet is a long-term wager placed well before an event resolves — like betting on a championship winner before the season starts, or an MVP award months before voting. Futures odds shift over time as the season progresses, so early bets on longshots can lock in much better prices than waiting.",
    "can-you-really-bet-one-dollar": "Yes, you can really bet just $1. Kalshi's minimum contract purchase is $1. Polymarket has no minimum. Most major sportsbooks accept $1 bets on standard markets. The $1 entry point is real — it's not a hypothetical framing. One dollar gets you into thousands of active markets across sports, politics, crypto, and culture.",
}

updated = 0
for filepath in sorted(glob.glob('content/**/*.json', recursive=True)):
    with open(filepath) as f:
        data = json.load(f)
    slug = data.get('slug', '')
    if slug in QUICK_ANSWERS and not data.get('quick_answer'):
        data['quick_answer'] = QUICK_ANSWERS[slug]
        with open(filepath, 'w') as f:
            json.dump(data, f, indent=2, ensure_ascii=False)
            f.write('\n')
        updated += 1
        print(f'Added QA: {slug}')

print(f'\nTotal: {updated} files updated')
