#!/usr/bin/env python3
"""
Dollar Bets — daily Telegram poster.

Reads the daily queue file (created by daily_tweets.py at 13:00 UTC) and posts
the same 3 cards to a Telegram channel AND/OR group. Single editorial decision,
single audit log, two delivery rails.

Env vars:
  TELEGRAM_BOT_TOKEN     required. From @BotFather.
  TELEGRAM_CHANNEL_ID    optional. Numeric (e.g. -1001234567890) or @channelname.
  TELEGRAM_GROUP_ID      optional. Numeric (e.g. -1001234567890).
                         At least one of CHANNEL_ID / GROUP_ID must be set.
  TELEGRAM_LIVE          "1" to actually post. Anything else = dry-run.

The queue file must already exist (it's created by the X workflow at the same
cron slot, 5 min earlier). If it doesn't exist, this script errors out — we
do NOT trigger a Claude selection here, to keep both platforms aligned on the
same 3 picks.
"""

import argparse
import json
import os
import sys
import urllib.error
import urllib.parse
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent  # site/
QUEUE_DIR = ROOT / "data" / "social-queue"

TG_API_BASE = "https://api.telegram.org"
TG_CAPTION_MAX = 1024


def log(msg: str) -> None:
    print(f"[telegram] {msg}", file=sys.stderr)


def utc_today() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d")


def read_queue_file(date: str) -> dict:
    path = QUEUE_DIR / f"{date}.json"
    if not path.exists():
        raise SystemExit(
            f"no queue file for {date} at {path}. "
            f"daily_tweets.py --mode select should run before this script."
        )
    return json.loads(path.read_text())


def write_queue_file(date: str, payload: dict) -> Path:
    path = QUEUE_DIR / f"{date}.json"
    path.write_text(json.dumps(payload, indent=2) + "\n")
    return path


# ── Telegram Bot API helpers ──────────────────────────────────────────────

def _tg_post_form(method: str, fields: dict) -> dict:
    """POST application/x-www-form-urlencoded to Telegram. Use this for
    sendPhoto-by-URL (Telegram fetches the photo from our public CDN)."""
    token = os.environ["TELEGRAM_BOT_TOKEN"]
    url = f"{TG_API_BASE}/bot{token}/{method}"
    body = urllib.parse.urlencode(fields).encode()
    req = urllib.request.Request(
        url, data=body, method="POST",
        headers={"Content-Type": "application/x-www-form-urlencoded"},
    )
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            return json.loads(resp.read().decode())
    except urllib.error.HTTPError as e:
        err_body = e.read().decode() if e.fp else "(no body)"
        raise SystemExit(f"Telegram API {method} failed HTTP {e.code}: {err_body[:400]}")


def send_photo_by_url(chat_id: str, photo_url: str, caption_html: str) -> int:
    """sendPhoto with photo=<URL>. Telegram fetches and caches the image.

    Returns the new message_id. Raises SystemExit on Telegram error.
    """
    if len(caption_html) > TG_CAPTION_MAX:
        # Defense: should never trigger given our caption builder, but if a
        # very long title slips through, fail loudly rather than silently
        # truncating and breaking HTML tags mid-attribute.
        raise SystemExit(
            f"caption exceeds {TG_CAPTION_MAX} chars ({len(caption_html)}). "
            f"Fix build_telegram_caption_html before retrying."
        )
    result = _tg_post_form("sendPhoto", {
        "chat_id": chat_id,
        "photo": photo_url,
        "caption": caption_html,
        "parse_mode": "HTML",
    })
    if not result.get("ok"):
        raise SystemExit(f"Telegram sendPhoto returned not-ok: {json.dumps(result)[:400]}")
    return result["result"]["message_id"]


# ── Main per-slot post ────────────────────────────────────────────────────

TARGETS = [
    # (env var holding chat_id, queue-state key)
    ("TELEGRAM_CHANNEL_ID", "telegram_channel"),
    ("TELEGRAM_GROUP_ID", "telegram_group"),
]


def post_slot(date: str, slot: int) -> None:
    queue = read_queue_file(date)
    selections = queue.get("selections", [])
    if slot < 1 or slot > len(selections):
        raise SystemExit(f"slot {slot} out of range (queue has {len(selections)} entries)")
    entry = selections[slot - 1]

    caption = entry.get("content", {}).get("telegram_caption_html")
    image_url = entry.get("image_url")
    if not caption or not image_url:
        raise SystemExit(
            f"slot {slot} missing telegram_caption_html or image_url. "
            f"Was this queue file generated by an older daily_tweets.py?"
        )

    posts_state = entry.setdefault("posts", {})
    live = os.environ.get("TELEGRAM_LIVE") == "1"

    targets_attempted = 0
    targets_with_id = 0
    for env_var, state_key in TARGETS:
        chat_id = os.environ.get(env_var, "").strip()
        if not chat_id:
            log(f"{env_var} not set — skipping {state_key}")
            continue
        targets_with_id += 1
        platform_state = posts_state.setdefault(state_key, {
            "posted": False, "posted_at": None, "message_id": None,
        })
        if platform_state.get("posted"):
            log(f"slot {slot} already posted to {state_key} "
                f"(message_id={platform_state.get('message_id')}) — skipping")
            continue

        print("=" * 60)
        print(f"SLOT {slot}  [{state_key}]  chat_id={chat_id}  "
              f"({'LIVE' if live else 'DRY-RUN'})")
        print(f"image: {image_url}")
        print(f"-- caption (HTML, {len(caption)}/{TG_CAPTION_MAX} chars) --")
        print(caption)
        print("=" * 60)

        if not live:
            log("TELEGRAM_LIVE != 1 — not posting.")
            continue

        targets_attempted += 1
        message_id = send_photo_by_url(chat_id, image_url, caption)
        log(f"posted to {state_key}, message_id={message_id}")
        platform_state["posted"] = True
        platform_state["posted_at"] = datetime.now(timezone.utc).isoformat()
        platform_state["message_id"] = message_id

    if targets_with_id == 0:
        raise SystemExit(
            "Neither TELEGRAM_CHANNEL_ID nor TELEGRAM_GROUP_ID is set — "
            "nothing to post to."
        )

    if live and targets_attempted > 0:
        write_queue_file(date, queue)


def main() -> None:
    p = argparse.ArgumentParser(description="Dollar Bets daily Telegram poster")
    p.add_argument("--date", help="YYYY-MM-DD (defaults to UTC today)")
    p.add_argument("--slot", type=int, required=True, help="1-indexed slot (1, 2, or 3)")
    args = p.parse_args()
    post_slot(args.date or utc_today(), args.slot)


if __name__ == "__main__":
    main()
